In [11]:
import numpy as np

In [16]:
A1 = np.array([3, 4, 5])

In [17]:
print(A1)

[3 4 5]


In [22]:
A1.ndim

1

In [57]:
A2 = np.array(([0, 1, 2], [11, 3, 12]))

In [20]:
A2 

array([[ 0,  1,  2],
       [11,  3, 12]])

In [23]:
A2.ndim

2

In [24]:
Z = np.zeros(4)

In [25]:
Z 

array([0., 0., 0., 0.])

In [26]:
Z2 = np.zeros((5,5))

In [27]:
Z2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
X = np.ones(3)

In [29]:
X

array([1., 1., 1.])

In [56]:
Y = np.ones((5,5), dtype='int16')
Y

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [34]:
B = np.arange(1, 21, 2)
B 

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [35]:
L = np.linspace(1, 5, 50)
L 

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [36]:
V = np.logspace(10, 10, 50)

In [37]:
V 

array([1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10,
       1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10,
       1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10,
       1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10,
       1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10,
       1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10,
       1.e+10, 1.e+10])

In [40]:
C = np.full((2,2), 5.5)
C 

array([[5.5, 5.5],
       [5.5, 5.5]])

In [45]:
I = np.eye(5)

In [46]:
I 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
import random 

In [48]:
random.random() 

0.2296603336472266

In [50]:
X = np.random.random((3,4))

In [51]:
X 

array([[0.04974149, 0.08742914, 0.08259196, 0.92408195],
       [0.35767568, 0.16309059, 0.99908467, 0.27774502],
       [0.73377003, 0.78324063, 0.48447752, 0.70705131]])

In [54]:
np.random.rand(100)

array([0.20254676, 0.36318619, 0.41185875, 0.69274171, 0.61783824,
       0.29138536, 0.71719536, 0.963284  , 0.88070226, 0.15503938,
       0.72234751, 0.76165513, 0.57179518, 0.8882016 , 0.525614  ,
       0.37859901, 0.49602587, 0.54674094, 0.61214408, 0.8991043 ,
       0.74319114, 0.6250995 , 0.83579037, 0.3551259 , 0.7054263 ,
       0.26667171, 0.31421428, 0.27796562, 0.5494287 , 0.52169971,
       0.93569091, 0.72070828, 0.97511627, 0.21936339, 0.02698308,
       0.8896812 , 0.47247364, 0.60666483, 0.93833563, 0.17419768,
       0.25041011, 0.14170247, 0.232854  , 0.75229787, 0.18577545,
       0.60050241, 0.38424383, 0.08178392, 0.20496065, 0.92175762,
       0.02875202, 0.36501711, 0.93543077, 0.31657922, 0.71902434,
       0.75404786, 0.35269901, 0.9405926 , 0.35374773, 0.63148199,
       0.57629883, 0.37827812, 0.15369425, 0.67827725, 0.01054063,
       0.50877562, 0.33068437, 0.16246113, 0.25788704, 0.46512695,
       0.62990306, 0.42276325, 0.03994201, 0.39463374, 0.65652

In [60]:
X = np.linspace(1, 10, 50)
X 

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [61]:
# shape 
X.shape

(50,)

In [62]:
# ndim 
X.ndim

1

In [63]:
# dtypes 
X.dtype

dtype('float64')

In [67]:
X_new = X.astype('int64')
X_new

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

In [68]:
X_new.dtype

dtype('int64')

In [69]:
A = np.array([11, 12, 13, 14])

In [70]:
A[0]

11

In [71]:
A[1]

12

In [72]:
A[3]

14

In [75]:
A[-1]

14

In [76]:
A[-2]

13

In [77]:
A[1:2]

array([12])

In [78]:
A[1:3]

array([12, 13])

In [82]:
A = np.array(([11, 12, 13], [21, 22, 23], [31, 32, 33]))

In [83]:
A.ndim

2

In [84]:
A[0]

array([11, 12, 13])

In [85]:
A[1]

array([21, 22, 23])

In [86]:
A[2]

array([31, 32, 33])

In [90]:
A[0][-1]

13

In [91]:
A[1][2]

23

In [92]:
A 

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [93]:
A.max() 

33

In [94]:
A.max(axis=0)

array([31, 32, 33])

In [95]:
A.max(axis=1)

array([13, 23, 33])

In [96]:
A.sum() 

198

In [97]:
A.sum(axis=0)

array([63, 66, 69])

In [98]:
A.sum(axis=1)

array([36, 66, 96])

In [100]:
A = np.matrix("1, 2, 3; 10, 11, 12")

In [101]:
A 

matrix([[ 1,  2,  3],
        [10, 11, 12]])

In [102]:
A.ndim

2

In [103]:
A = np.matrix("11, 12, 13; 21, 22, 23; 31, 32, 33")

In [104]:
A 

matrix([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])

In [105]:
A.ndim

2

In [106]:
A.shape

(3, 3)

In [107]:
A.shape[0]

3

In [108]:
A.shape[1]

3

In [109]:
A.size

9

In [110]:
A.nbytes

72

In [113]:
X = np.arange(20).reshape(4, 5)

In [114]:
X 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [119]:
L = np.linspace(1, 10, 100).reshape(25,4)

In [120]:
L

array([[ 1.        ,  1.09090909,  1.18181818,  1.27272727],
       [ 1.36363636,  1.45454545,  1.54545455,  1.63636364],
       [ 1.72727273,  1.81818182,  1.90909091,  2.        ],
       [ 2.09090909,  2.18181818,  2.27272727,  2.36363636],
       [ 2.45454545,  2.54545455,  2.63636364,  2.72727273],
       [ 2.81818182,  2.90909091,  3.        ,  3.09090909],
       [ 3.18181818,  3.27272727,  3.36363636,  3.45454545],
       [ 3.54545455,  3.63636364,  3.72727273,  3.81818182],
       [ 3.90909091,  4.        ,  4.09090909,  4.18181818],
       [ 4.27272727,  4.36363636,  4.45454545,  4.54545455],
       [ 4.63636364,  4.72727273,  4.81818182,  4.90909091],
       [ 5.        ,  5.09090909,  5.18181818,  5.27272727],
       [ 5.36363636,  5.45454545,  5.54545455,  5.63636364],
       [ 5.72727273,  5.81818182,  5.90909091,  6.        ],
       [ 6.09090909,  6.18181818,  6.27272727,  6.36363636],
       [ 6.45454545,  6.54545455,  6.63636364,  6.72727273],
       [ 6.81818182,  6.

In [124]:
Y = np.array([[[11, 12], [21, 22]], [[31, 32], [41, 42]]])

In [126]:
Y

array([[[11, 12],
        [21, 22]],

       [[31, 32],
        [41, 42]]])

In [130]:
Y[0][0][0]

11

In [128]:
Y[1]

array([[31, 32],
       [41, 42]])